# Generated by Django 4.2.28 on 2026-02-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='URL nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='products/', verbose_name='Rasm')),
                ('nomi', models.CharField(max_length=200, verbose_name='Nomi')),
                ('tavsifi', models.TextField(verbose_name='Tavsifi')),
                ('yaratilgan_vaqti', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='core.kategoriya', verbose_name='Kategoriya')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramFoydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True)),
                ('telefon_raqam', models.CharField(max_length=20)),
                ('yaratilgan_vaqti', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TasdiqlovchiSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(verbose_name='Nechta kod chiqarish kerak')),
                ('yaratilgan_vaqti', models.DateTimeField(auto_now_add=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mahsulot', verbose_name='Mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='TasdiqlovchiKod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('ishlatilgan', models.BooleanField(default=False)),
                ('tekshirilgan_vaqti', models.DateTimeField(blank=True, null=True)),
                ('tasdiqlovchi_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kodlar', to='core.tasdiqlovchiset')),
                ('tekshirgan_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.telegramfoydalanuvchi')),
            ],
        ),
        migrations.CreateModel(
            name='MahsulotXususiyati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xususiyatlar', to='core.mahsulot', verbose_name='Mahsulot')),
            ],
        ),
    ]
