# Generated by Django 4.2.28 on 2026-02-17 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avtomobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='URL nomi')),
            ],
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='avtomobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='core.avtomobile', verbose_name='Avtomobil'),
        ),
    ]
