# Generated by Django 4.2.28 on 2026-02-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_avtomobile_mahsulot_avtomobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='avtomobile',
        ),
        migrations.DeleteModel(
            name='Avtomobile',
        ),
    ]
