# Generated by Django 4.2.28 on 2026-02-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_mahsulot_avtomobile_delete_avtomobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='kategoriya',
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='kategoriyalar',
            field=models.ManyToManyField(related_name='mahsulotlar', to='core.kategoriya', verbose_name='Kategoriyalar'),
        ),
    ]
