# Generated by Django 4.2.28 on 2026-02-17 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_mahsulot_kategoriya_mahsulot_kategoriyalar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='rasm',
        ),
        migrations.CreateModel(
            name='MahsulotRasmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='products/', verbose_name='Rasm')),
                ('asosiy', models.BooleanField(default=False)),
                ('yuklangan_vaqti', models.DateTimeField(auto_now_add=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='core.mahsulot', verbose_name='Mahsulot')),
            ],
        ),
    ]
