# Generated by Django 4.2.28 on 2026-02-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_mahsulot_rasm_mahsulotrasmi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoriya',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='mahsulot',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='mahsulotrasmi',
            options={'verbose_name': 'Mahsulot rasmi', 'verbose_name_plural': 'Mahsulot rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='mahsulotxususiyati',
            options={'verbose_name': 'Mahsulot xususiyati', 'verbose_name_plural': 'Mahsulot xususiyatlari'},
        ),
        migrations.AlterModelOptions(
            name='tasdiqlovchikod',
            options={'verbose_name': 'Etiketka kod', 'verbose_name_plural': 'Etiketka kodlari'},
        ),
        migrations.AlterModelOptions(
            name='tasdiqlovchiset',
            options={'verbose_name': 'Etiketka', 'verbose_name_plural': 'Etiketkalar'},
        ),
        migrations.AlterModelOptions(
            name='telegramfoydalanuvchi',
            options={'verbose_name': 'Telegram foydalanuvchisi', 'verbose_name_plural': 'Telegram foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='tasdiqlovchiset',
            name='soni',
            field=models.IntegerField(verbose_name='Etiketka soni'),
        ),
    ]
