# Generated by Django 4.2.28 on 2026-02-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_kategoriya_options_alter_mahsulot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avtomobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150, verbose_name='Avtomobil nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='URL nomi')),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
            },
        ),
        migrations.CreateModel(
            name='MahsulotKategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='URL nomi')),
            ],
            options={
                'verbose_name': 'Mahsulot kategoriyasi',
                'verbose_name_plural': 'Mahsulot kategoriyalari',
            },
        ),
        migrations.AlterModelOptions(
            name='mahsulot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mahsulotrasmi',
            options={'verbose_name': 'Mahsulot rasmi ', 'verbose_name_plural': 'Mahsulot rasmlari '},
        ),
        migrations.AlterModelOptions(
            name='mahsulotxususiyati',
            options={'verbose_name': 'Mahsulot xususiyati ', 'verbose_name_plural': 'Mahsulot xususiyatlari '},
        ),
        migrations.AlterModelOptions(
            name='tasdiqlovchikod',
            options={'verbose_name': 'Etiketka kod ', 'verbose_name_plural': 'Etiketka kodlari '},
        ),
        migrations.AlterModelOptions(
            name='tasdiqlovchiset',
            options={'verbose_name': 'Etiketka ', 'verbose_name_plural': 'Etiketkalar '},
        ),
        migrations.AlterModelOptions(
            name='telegramfoydalanuvchi',
            options={'verbose_name': 'Telegram foydalanuvchisi ', 'verbose_name_plural': 'Telegram foydalanuvchilar '},
        ),
        migrations.RemoveField(
            model_name='mahsulot',
            name='kategoriyalar',
        ),
        migrations.AlterField(
            model_name='mahsulotrasmi',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='core.mahsulot', verbose_name='Mahsulot '),
        ),
        migrations.AlterField(
            model_name='mahsulotxususiyati',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xususiyatlar', to='core.mahsulot', verbose_name='Mahsulot '),
        ),
        migrations.DeleteModel(
            name='Kategoriya',
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='avtomobillar',
            field=models.ManyToManyField(blank=True, related_name='mahsulotlar', to='core.avtomobil', verbose_name='Mos avtomobillar'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='mahsulot_kategoriyasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mahsulotkategoriya', verbose_name='Mahsulot kategoriyasi'),
        ),
    ]
