# Generated by Django 4.2.28 on 2026-02-28 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_mahsulotkategoriya_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahsulot',
            options={'verbose_name': 'Mahsulot ', 'verbose_name_plural': 'Mahsulotlar '},
        ),
        migrations.AlterModelOptions(
            name='mahsulotkategoriya',
            options={'verbose_name': 'Kategoriyasi ', 'verbose_name_plural': 'Kategoriyalari '},
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='avtomobillar',
            field=models.ManyToManyField(blank=True, related_name='mahsulotlar', to='core.avtomobil', verbose_name='Avtomobillar '),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='mahsulot_kategoriyasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mahsulotkategoriya', verbose_name='Kategoriyasi '),
        ),
    ]
