# Generated by Django 4.2.28 on 2026-03-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_mahsulot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasdiqlovchiset',
            name='mahsulot',
        ),
    ]
